baseURL = "http://lifestyle.gadgetuni.com/"
googleAnalytics = ""
languageCode = "en-us"
theme = "forty"
title = "Forty"
[params]
custom_css = []
custom_js = []
description = "Your description"
favicon = "favicon.ico"
image = ""
name = "Your name"
[params.banner]
buttontext = "Get Started"
subtitle = "Our mission at Gadgetuni is to create a life less complicated for all our customers and at the same time as helping hand in lifestyle optimization."
title = "GadgetUni"
[params.contact]
buttonclear = "Clear"
buttonsend = "Send message"
enable = true
[[params.contact.address]]
city = "City, ST 00000"
country = "Country"
street = "Street"
title = "Address"
[[params.contact.email]]
email = "example@domain.com"
title = "Email"
[[params.contact.phone]]
phone = "(000) 000-0000 x1234"
title = "Phone"
[params.error404]
heading = "Page couldn't be found"
text = "Please visit [this page](/)"
[params.footer]
copyright = "2017 GadgetUni v0.1"
enable = true
[[params.footer.social]]
icon = "fa-facebook"
label = "Facebook"
url = "https://facebook.com/gadgetuni"
[[params.footer.social]]
icon = "fa-instagram"
label = "Instagram"
url = "https://www.instagram.com/gadgetuni"
[params.homepagebottom]
enable = true
[params.homepagetop]
enable = true
[params.inpageads]
enable = true
[params.navigation]
menu = "Menu"
subtitle = "By HTML5 Up"
title = "Forty"
[[params.navigation.button1]]
name = "Get Started"
url = "blogs"
[[params.navigation.button2]]
name = "Log In"
url = "#"
[[params.navigation.links]]
name = "Home"
url = "#"
[[params.navigation.links]]
name = "Blogs"
url = "blogs"
[[params.navigation.links]]
name = "Products"
url = "products/"
[params.tiles]
enable = true
[[params.tiles.showcase]]
image = "New-3-Season.jpg"
subtitle = "Imagine yourself on a beautiful beach, or next to the..."
title = "Inflatable Sofa"
url = "products/inflatable-sofa"
[[params.tiles.showcase]]
image = "Roller-Sushi-Roll-Mold-Making-Kit-Tools-Sushi-Bazooka-Rice-Meat-Vegetables-DIY-Making-Kitchen-Gadgets_d024680b-0afd-411a-8045-f1e35aad89d8_2000x.jpg"
subtitle = "You don’t know what to prepare for a dinner..."
title = "Sushi Bazooka"
url = "blogs/bazooka"
[[params.tiles.showcase]]
image = "blue_2000x.jpg"
subtitle = "50% OFF LIMITED TIME OFFER"
title = "Portable Blender"
url = "products/blender"
[[params.tiles.showcase]]
image = "blog2.jpg"
subtitle = "Here in Gadgetuni, we’ve found some items that can help to improve ..."
title = "TOP 5 GADGETS FOR HEALTHY LIFESTYLE"
url = "blogs/top-5-gadgets-lifestyle"
[[params.tiles.showcase]]
image = "blog1.jpeg"
subtitle = "Some of us love to travel alone, the others go with ..."
title = "TOP GADGETS FOR SURVIVING A ROAD TRIP"
url = "blogs/top-5-gadgets-survival"
[params.two]
buttontext = "Get Started"
enable = true
subtitle = "For questions regarding our products or anything we can help with send us an email at support@gadgetuni.com or contact us on Facebook!"
title = "About Us"
url = "blogs"
