---
hide_body: true
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: This is a test
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: false
- type: textarea
  default: tes test test
